### ISSUE TITLE
[1.19.1/2 Doesn't work] Server Crashes as Soon as any Player Tries to Join

### ISSUE THREAD

**Issue by LunchBox951** [LimeShulkerBox/fabric-discord-chat-and-console#5]
As the title says, whenever a player tries to join the same error message prints out:

[12:59:15] [Server thread/INFO]: LunchBox951[/10.0.0.129:61634] logged in with entity id 125 at (5001.300000011921, 67.0, 2108.699999988079)
[12:59:15] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.AbstractMethodError: Receiver class com.limeshulkerbox.fabricord.minecraft.ServerInitializer$$Lambda$3493/0x00000008015bd860 does not define or inherit an implementation of the resolved method 'abstract void onGameMessage(net.minecraft.server.MinecraftServer, net.minecraft.class_2561, boolean)' of interface net.fabricmc.fabric.api.message.v1.ServerMessageEvents$GameMessage.
        at net.fabricmc.fabric.api.message.v1.ServerMessageEvents.lambda$static$8(ServerMessageEvents.java:111) ~[fabric-message-api-v1-5.0.1+4e0178f495-8ebc37b437c8b20.jar:?]
        at net.minecraft.class_3324.handler$zoa000$onSendGameMessage(class_3324.java:4048) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_43512(class_3324.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_43514(class_3324.java:784) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_14570(class_3324.java:221) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_33800(class_3248.java:158) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_14384(class_3248.java:145) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.redirect$zoh000$handlePlayerJoin(class_3248.java:563) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_18784(class_3248.java:80) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:248) ~[server-intermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:289) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zbe000$modifiedRunLoop(MinecraftServer.java:2885) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[12:59:15] [Server thread/ERROR]: This crash report has been saved to: E:\Games\Minecraft Server 2 Electric Boogaloo\.\crash-reports\crash-2022-08-04_12.59.15-server.txt
[12:59:15] [Server thread/INFO]: Stopping server
[12:59:15] [Server thread/INFO]: Saving players
[12:59:15] [Server thread/INFO]: Saving worlds
[12:59:17] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[12:59:17] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[12:59:17] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[12:59:17] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[12:59:17] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[12:59:17] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[12:59:17] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[13:00:17] [Server Watchdog/ERROR]: A single server tick took 60.00 seconds (should be max 0.05)
[13:00:17] [Server Watchdog/ERROR]: Considering it to be crashed, server will forcibly shutdown.
`

Attached is the crash report.
[crash-2022-08-04_13.00.17-server.txt](https://github.com/LimeShulkerBox/fabricord/files/9261822/crash-2022-08-04_13.00.17-server.txt)

**Comment by FaceCutter** [comment]
Same(

**Comment by piemanau** [comment]
Please provide your config making sure remove the bot token and the webhook URL.

**Comment by piemanau** [comment]
Ah I just re read the crash report, it says that you are using 1.19.1, I am not supporting that just yet, it is on the way though.

**Comment by piemanau** [comment]
1.19.2 has been released
